install_data(join_paths(meson.current_source_dir(), 'black_on_light_yellow.color_scheme'), install_dir: join_paths(get_option('prefix'), get_option('datadir'), 'terminus'))
install_data(join_paths(meson.current_source_dir(), 'black_on_white.color_scheme'), install_dir: join_paths(get_option('prefix'), get_option('datadir'), 'terminus'))
install_data(join_paths(meson.current_source_dir(), 'gray_on_black.color_scheme'), install_dir: join_paths(get_option('prefix'), get_option('datadir'), 'terminus'))
install_data(join_paths(meson.current_source_dir(), 'green_on_black.color_scheme'), install_dir: join_paths(get_option('prefix'), get_option('datadir'), 'terminus'))
install_data(join_paths(meson.current_source_dir(), 'orange_on_black.color_scheme'), install_dir: join_paths(get_option('prefix'), get_option('datadir'), 'terminus'))
install_data(join_paths(meson.current_source_dir(), 'dark_solar.color_scheme'), install_dir: join_paths(get_option('prefix'), get_option('datadir'), 'terminus'))
install_data(join_paths(meson.current_source_dir(), 'white_on_black.color_scheme'), install_dir: join_paths(get_option('prefix'), get_option('datadir'), 'terminus'))
install_data(join_paths(meson.current_source_dir(), 'solar.color_scheme'), install_dir: join_paths(get_option('prefix'), get_option('datadir'), 'terminus'))
install_data(join_paths(meson.current_source_dir(), 'light_solar.color_scheme'), install_dir: join_paths(get_option('prefix'), get_option('datadir'), 'terminus'))
install_data(join_paths(meson.current_source_dir(), 'tango.color_scheme'), install_dir: join_paths(get_option('prefix'), get_option('datadir'), 'terminus'))
install_data(join_paths(meson.current_source_dir(), 'linux_console.color_scheme'), install_dir: join_paths(get_option('prefix'), get_option('datadir'), 'terminus'))
install_data(join_paths(meson.current_source_dir(), 'terminal.color_scheme'), install_dir: join_paths(get_option('prefix'), get_option('datadir'), 'terminus'))
install_data(join_paths(meson.current_source_dir(), 'rxvt.color_scheme'), install_dir: join_paths(get_option('prefix'), get_option('datadir'), 'terminus'))
install_data(join_paths(meson.current_source_dir(), 'solarized.color_scheme'), install_dir: join_paths(get_option('prefix'), get_option('datadir'), 'terminus'))
install_data(join_paths(meson.current_source_dir(), 'test/prueba.txt'), install_dir: join_paths(get_option('prefix'), get_option('datadir'), 'terminus'))
