#!/bin/sh

set -e

case "$1" in
    configure)
        # Alternatives
        update-alternatives --quiet \
            --install /usr/bin/x-terminal-emulator \
	      x-terminal-emulator /usr/bin/terminus 20
        ;;
esac
